# Generated by Django 4.1.5 on 2023-01-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='task_id',
            new_name='NumofTasks',
        ),
    ]
