# Generated by Django 4.1.5 on 2023-01-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_task_id_todoitem_numoftasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='NumofTasks',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='tasks',
            field=models.CharField(max_length=100),
        ),
    ]
