# Generated by Django 4.1.5 on 2023-01-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_todoitem_numoftasks_alter_todoitem_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='category',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='tasks',
            new_name='todo',
        ),
    ]
