# Generated by Django 4.1.5 on 2023-01-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_checklist_checklistitem_remove_todoitem_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='is_archived',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='checklistitem',
            old_name='is_checked',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='is_deleted',
        ),
    ]
