# Generated by Django 4.1.5 on 2023-01-24 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_rename_is_archived_checklist_completed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckListItem',
            new_name='ListItem',
        ),
    ]
