# Generated by Django 4.1.5 on 2023-01-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_checklistitem_listitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='updated_on',
        ),
    ]
